Ordre aléatoire des têtes du Royaume
Royaume-Group/Royaume-Frontend pull request #59
Opened 2023-06-21 23:53 UTC by Steellgold

J'ai remarqué que les photos de profiles était tout le temps aligné dans le même ordre et je trouve sa pas très esthétique

J'ai donc fait en sorte qu'elles soit mélangé pour ajouter un peu plus de réalisme 

Avant vs Après
![image](https://github.com/Virtual-Royaume/Royaume-Frontend/assets/51505384/bd34556b-332b-4497-97e1-25dea54f5dd4)
![image](https://github.com/Virtual-Royaume/Royaume-Frontend/assets/51505384/c67e7a8a-9a8c-46fa-9791-2e2537d61432)

Capture d'écrans prise au moment du rechargement de page

2023-06-21 23:57 UTC, Bluzzi requested changes
L'objectif de ce genre de données c'est juste d'avoir une preview du résultat final sans ajouter de complexité au code.

Si on en ajoute trop, le refactor sera + complexe quand on va connecter le site à l'API.

2023-06-21 23:58 UTC, Steellgold commented
> L'objectif de ce genre de données c'est juste d'avoir une preview du résultat final sans ajouter de complexité au code.
> 
> Si on en ajoute trop, le refactor sera + complexe quand on va connecter le site à l'API.

Je pense pas que cela rend + difficile au passage à l'API c'est simplement un tableau qu'on donne à la fonction donc il sera du même type qu'actuellement

2023-06-22 00:03 UTC, Bluzzi commented
Ça peut porter à confusion pour le dev qui s’en occupera, il ne sera pas quoi faire de cette fonction.

Pareil si on crée ce genre de fonction, il faut l’accompagner de test unitaire. Aucune fonction de ce type ne doit pas en avoir.

2023-06-22 00:04 UTC, Steellgold commented
> Ça peut porter à confusion pour le dev qui s’en occupera, il ne sera pas quoi faire de cette fonction.
> 
> Pareil si on crée ce genre de fonction, il faut l’accompagner de test unitaire. Aucune fonction de ce type ne doit pas en avoir.

@Bluzzi Si je fait un test unitaire et que la fonction je la met donc à part dans un dossier (surement /utils) cela peut aider ?

2023-06-22 00:05 UTC, Bluzzi commented
C'est déjà + ok, ça m'embête de prendre du temps sur un truc pas forcément permanent, mais oui tu peux.

2023-06-22 00:06 UTC, Steellgold commented
> C'est déjà + ok, ça m'embête de prendre du temps sur un truc pas forcément permanent, mais oui tu peux.

@Bluzzi Ce n'est pas pertinent mais pour un visiteur lambda se serra + beau que répéter dans le même ordre constant

2023-06-22 08:48 UTC, Bluzzi requested changes

2023-06-22 08:48 UTC, Bluzzi commented on src/lib/utils/members-shuffle/members-shuffle.ts
> +};
La réutilisabilité ! Pourquoi se limiter à une array de `Member` quand on pourrait avoir une fonction permettant de shuffle n'importe quoi ?

2023-06-22 08:48 UTC, Bluzzi commented on src/lib/utils/members-shuffle/members-shuffle.test.ts
> +});
Il faut aller plus loin, voici quelques tests à écrire :
- vérification de la non-mutabilité de la fonction
- vérification de la valeur de retour avec un mock de `Math.random` pour que ça sois prévisible 
- vérifier que l'array mélangé contient chaque élément de l'array précédente 
- vérifie que l'array a la même taille que l'array précédente 

Aussi, il ne faut pas utiliser `toBe()` mais `toEqual`, car `toBe` vérifie aussi l'authenticité de l'array, ici on veux juste vérifier leur contenu (donc dans ton actuel actuel le premier test ne pourra jamais fail).

N'utilise pas une de nos configurations mais directement une array (voir plusieurs) que tu créé dans le fichier de test, assure toi d'avoir au moins 8 valeurs dans l'array pour limiter un maximum les fails du test du à la mal chance d'un mélange qui retournerais la même array ahah.

8 valeurs ça fait 16 777 216 possibilités, ça me semble est suffisamment sur tout en restant pas trop lourd.

2023-06-22 11:30 UTC, Steellgold commented on src/lib/utils/members-shuffle/members-shuffle.ts
> +};
Oui effectivement j'y ai pas pensé directement, j'ai modifié et fait en sorte que l'on puisse mettre n'importe quel type de tableau dedans

2023-06-24 19:44 UTC, Bluzzi requested changes

2023-06-24 19:44 UTC, Bluzzi commented on src/lib/utils/shuffle/shuffle.test.ts
> +describe("shuffle function", () => {
Parmis les tests que j'ai cité dans la review précédente, tu ne test pas :
- vérification de la non-mutabilité de la fonction
- vérifier que l'array mélangé contient chaque élément de l'array précédente (peut-être que si, mais j'aimerais un `it` bien nommé par test d'écrit précédemment)

2023-06-24 19:44 UTC, Bluzzi commented on src/lib/utils/shuffle/shuffle.test.ts
> +    expect(shuffled.length).toEqual(array.length);
Certains des tests suivant doivent être split pour avoir un nom bien conforme à ce qui est testé.

2023-06-24 19:44 UTC, Bluzzi commented on src/lib/utils/shuffle/shuffle.test.ts
> +    expect(shuffle([])).toEqual([]); // logika
Même si c'est drôle, restons pro :p

2023-06-24 19:44 UTC, Bluzzi commented on src/lib/utils/shuffle/shuffle.test.ts
> +describe("shuffle function", () => {
Ok je viens de voir que c'est vérifie plus bas quand même. Malgré ça, split d'avantage les tests, même si le code est souvent explicite, l'objectif et de pouvoir fix une erreur juste en connaissant le message du test qui a fail.

2024-07-13 21:51 UTC, closed without merging